[package]
name = "rag"
version = "0.1.0"
authors = ["Lachlan McCalman <lachlan@gradientinstitute.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
dialoguer = "0.5"
console = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
